### ISSUE TITLE
Feature: Support Message Signing with Sparrow Wallet

### ISSUE THREAD

**Issue by its-DomeE** [KeystoneHQ/keystone3-firmware#1127]
Most BTC brokers require a signed message to confirm ownership, if you want to buy BTC directly to your wallet. 

The Sparrow Wallet supports message signing, even via qr-code.

In my opinion, this is an important feature for a hardware wallet to support. That's why it would be awesome to have this addition to the Keystone Wallet.

**Comment by soralit** [comment]
@its-DomeE Thanks for suggestion, after some researching and discussion, we push this to our planned features.
