### ISSUE TITLE
Solflare Solana raw message in swap confirmation

### ISSUE THREAD

**Issue by zz64** [KeystoneHQ/keystone3-firmware#485]
Hi,
in SOLANA using Solflare, when i swap from token to token i get only raw message.
how can i trust transaction ?

![solflare_Solana_Swap](https://github.com/KeystoneHQ/keystone3-firmware/assets/1113878/ee28c83b-2a40-484a-aac0-501b9dc9d898)

Can i place SOLANA token address database in sdcard folder to give information to Keystone ?
like [ERC20](https://support.keyst.one/advanced-features/decode-defi-transactions)
any guide for this please ?

Thanks.

**Comment by soralit** [comment]
Hey @zz64 , thanks for your feedback, currently such messages are not able to decoding and we're scheduling an improvement on Solana transaction parsing.

**Comment by soralit** [comment]
Close this issue for we have recorded it into our internal channel. Really appreciate for your advice.
