### ISSUE TITLE
[Typo] Typo on the boot screen. (Keystone 3 Pro Bitcoin-Only Firmware)

### ISSUE THREAD

**Issue by mildobread** [KeystoneHQ/keystone3-firmware#727]
When updating the Keystone 3 Pro Bitcoin-Only Firmware (released on April 2, 2024), there is a typo on the boot screen.
It says 'Bitcion Only' instead of 'Bitcoin Only'.

**Comment by soralit** [comment]
Thanks for sharing this. We have fixed the typo.
