### ISSUE TITLE
Side effects of boot img patch.

### ISSUE THREAD

**Issue by mildobread** [KeystoneHQ/keystone3-firmware#731]
After applying boot logo typo patch below, distortion and blurring are visible in both the boot logo image and font.
https://github.com/KeystoneHQ/keystone3-firmware/pull/729/commits/c773983d04911d361f1456358f829157760f4738
And the resolution has also significantly decreased.
![bug](https://github.com/KeystoneHQ/keystone3-firmware/assets/155842339/1ac1a09d-a50d-40f7-9d1d-ebc650fd18eb)

**Comment by ww3512687** [comment]
@mildobread Thanks for reporting this. We will fix it as soon as possible
